- name: install basic utils, shells, apps
  community.general.apk:
    name: "{{ apk.pkgs }}"
    update_cache: true
  become: yes

- name: Enable and start service sshd
  ansible.builtin.service:
    name: "{{ service.name }}"
    state: started
    enabled: yes
  become: yes

